<?php

/* custom routes generated by CRUD */

Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('pages', 'PagesController');
	Route::get('pages/{id}/delete', array('as' => 'admin.pages.delete', 'uses' => 'PagesController@getDelete'));
	Route::get('pages/{id}/confirm-delete', array('as' => 'admin.pages.confirm-delete', 'uses' => 'PagesController@getModalDelete'));
});


Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelSalbar'), function () {
    # Dashboard / Index
	Route::get('/', array('as' => 'dashboard','uses' => 'JoshController@showHome'));

		Route::resource('sazutailanmayagts', 'SazutailanmayagtsController');
		Route::get('sazutailanmayagts/{id}/delete', array('as' => 'admin.sazutailanmayagts.delete', 'uses' => 'SazutailanmayagtsController@getDelete'));
		Route::get('sazutailanmayagts/{id}/confirm-delete', array('as' => 'admin.sazutailanmayagts.confirm-delete', 'uses' => 'SazutailanmayagtsController@getModalDelete'));


		Route::resource('tsusanbuteegdehuuntailans', 'TsusanbuteegdehuuntailansController');
		Route::get('tsusanbuteegdehuuntailans/{id}/delete', array('as' => 'admin.tsusanbuteegdehuuntailans.delete', 'uses' => 'TsusanbuteegdehuuntailansController@getDelete'));
		Route::get('tsusanbuteegdehuuntailans/{id}/confirm-delete', array('as' => 'admin.tsusanbuteegdehuuntailans.confirm-delete', 'uses' => 'TsusanbuteegdehuuntailansController@getModalDelete'));




		Route::resource('hereglesen_tstsb_tasagaars', 'Hereglesen_tstsb_tasagaarsController');
		Route::get('hereglesen_tstsb_tasagaars/{id}/delete', array('as' => 'admin.hereglesen_tstsb_tasagaars.delete', 'uses' => 'Hereglesen_tstsb_tasagaarsController@getDelete'));
		Route::get('hereglesen_tstsb_tasagaars/{id}/confirm-delete', array('as' => 'admin.hereglesen_tstsb_tasagaars.confirm-delete', 'uses' => 'Hereglesen_tstsb_tasagaarsController@getModalDelete'));


		Route::resource('hun_huchnii_tailans', 'Hun_huchnii_tailansController');
		Route::get('hun_huchnii_tailans/{id}/delete', array('as' => 'admin.hun_huchnii_tailans.delete', 'uses' => 'Hun_huchnii_tailansController@getDelete'));
		Route::get('hun_huchnii_tailans/{id}/confirm-delete', array('as' => 'admin.hun_huchnii_tailans.confirm-delete', 'uses' => 'Hun_huchnii_tailansController@getModalDelete'));


		Route::resource('surgaltand_hamragdaltiin_tailans', 'Surgaltand_hamragdaltiin_tailansController');
		Route::get('surgaltand_hamragdaltiin_tailans/{id}/delete', array('as' => 'admin.surgaltand_hamragdaltiin_tailans.delete', 'uses' => 'Surgaltand_hamragdaltiin_tailansController@getDelete'));
		Route::get('surgaltand_hamragdaltiin_tailans/{id}/confirm-delete', array('as' => 'admin.surgaltand_hamragdaltiin_tailans.confirm-delete', 'uses' => 'Surgaltand_hamragdaltiin_tailansController@getModalDelete'));



});